export const CONTACT_SHOW = 'CONTACT_SHOW';
export const CONTACT_HIDE = 'CONTACT_HIDE';
export const CONTACT_POSTING = 'CONTACT_POSTING';
export const CONTACT_POST_SUCCESS = 'CONTACT_POST_SUCCESS';
export const CONTACT_POST_FAILED = 'CONTACT_POST_FAILED';

export const SUBSCRIBE_SHOW = 'SUBSCRIBE_SHOW';
export const SUBSCRIBE_HIDE = 'SUBSCRIBE_HIDE';
export const SUBSCRIBE_POSTING = 'SUBSCRIBE_POSTING';
export const SUBSCRIBE_POST_SUCCESS = 'SUBSCRIBE_POST_SUCCESS';
export const SUBSCRIBE_POST_FAILED = 'SUBSCRIBE_POST_FAILED';


export const ART_REQUESTED = 'ART_REQUESTED';
export const ART_SUCCESS = 'ART_SUCCESS';
export const ART_FAILED = 'ART_FAILED';

export const BLOG_REQUESTED = 'BLOG_REQUESTED';
export const BLOG_SUCCESS = 'BLOG_SUCCESS';
export const BLOG_FAILED = 'BLOG_FAILED';

export const SHOW_REQUESTED = 'SHOW_REQUESTED';
export const SHOW_SUCCESS = 'SHOW_SUCCESS';
export const SHOW_FAILED = 'SHOW_FAILED';
export const SHOW_NEXT = 'SHOW_NEXT';
export const SHOW_PREV = 'SHOW_PREV';

export const FEATURE_REQUESTED = 'FEATURE_REQUESTED';
export const FEATURE_SUCCESS = 'FEATURE_SUCCESS';
export const FEATURE_FAILED = 'FEATURE_FAILED';
