
export const GALLERIES_REQUESTED = 'GALLERIES_REQUESTED';
export const GALLERIES_SUCCESS = 'GALLERIES_SUCCESS';
export const GALLERIES_FAILED = 'GALLERIES_FAILED';

export const ART_REQUESTED = 'ART_REQUESTED';
export const ART_SUCCESS = 'ART_SUCCESS';
export const ART_FAILED = 'ART_FAILED';

export const BLOG_REQUESTED = 'BLOG_REQUESTED';
export const BLOG_SUCCESS = 'BLOG_SUCCESS';
export const BLOG_FAILED = 'BLOG_FAILED';
