export const INDEX_REQUESTED = 'INDEX_REQUESTED';
export const INDEX_RECEIVED = 'INDEX_RECEIVED';
export const UPDATE_INDEX = 'UPDATE_INDEX';

export const CHAPTER_REQUESTED = 'CHAPTER_REQUESTED';
export const CHAPTER_RECEIVED = 'CHAPTER_RECEIVED';
export const UPDATE_CHAPTER = 'UPDATE_CHAPTER';


export const GALLERIES_REQUESTED = 'GALLERIES_REQUESTED';
export const GALLERIES_RECEIVED = 'GALLERIES_RECEIVED';
export const UPDATE_GALLERIES = 'UPDATE_GALLERIES';

export const ART_REQUESTED = 'ART_REQUESTED';
export const ART_RECEIVED = 'ART_RECEIVED';
export const UPDATE_ART = 'UPDATE_ART';
