export const INDEX_REQUESTED = 'INDEX_REQUESTED';
export const INDEX_RECEIVED = 'INDEX_RECEIVED';
export const UPDATE_INDEX = 'UPDATE_INDEX';

export const CHAPTER_REQUESTED = 'CHAPTER_REQUESTED';
export const CHAPTER_RECEIVED = 'CHAPTER_RECEIVED';
export const UPDATE_CHAPTER = 'UPDATE_CHAPTER';
