
export const GALLERIES_REQUESTED = 'GALLERIES_REQUESTED';
export const GALLERIES_RECEIVED = 'GALLERIES_RECEIVED';
export const UPDATE_GALLERIES = 'UPDATE_GALLERIES';

export const ART_REQUESTED = 'ART_REQUESTED';
export const ART_RECEIVED = 'ART_RECEIVED';
export const UPDATE_ART = 'UPDATE_ART';
